### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by theXappy** [samsonpianofingers/ClassDumper2#2]
Hello :)
Just found your project today and I really liked it!

I have my own (free and open source) project on GH called "RemoteNET", it does something similar but for .NET executables.
I'd like to add your code to my project to create a unified research tool for both native and managed executables.
Usually I'd refer to the project's license to see if the developer is fine with it but I didn't see one in your repo.
Can you tell me if you had a license in mind? or maybe grant me explicit permission to include your code?

Thanks

**Comment by GrandpaGameHacker** [comment]
Hello! of course you can include the code in your project and/or use it as a reference
You have my explicit permission

I will say the code only works with MSVC compiled code
Sorry about no licence I never thought my code would be used by many people
Thankyou

**Comment by theXappy** [comment]
Awesome, thank you!
I'll make sure to give you credit if it all works out :)
